# Generated by Django 4.2.5 on 2023-09-27 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resturant', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='password',
            field=models.CharField(default='jhgjhfjh', max_length=15),
            preserve_default=False,
        ),
    ]
