# Generated by Django 4.2.5 on 2023-09-27 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resturant', '0003_categorys_products'),
    ]

    operations = [
        migrations.RenameField(
            model_name='products',
            old_name='category',
            new_name='category_name',
        ),
    ]
