# Generated by Django 4.2.5 on 2023-09-28 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resturant', '0006_alter_products_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/'),
        ),
    ]
